import Head from "next/head";
import SignIn from "./login/signIn";
export default function Home() {
  return (
    <>
      <Head>
        <title>weekly</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
