import Head from "next/head";
import LoginPage from "./Login";
import Input from "@/src/components/common/input/input";
import LoginBox from "@/src/components/pageComponent/login/loginBox";
export default function Home() {
  return (
    <>
      <Head>
        <title>weekly</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <LoginBox />
      </main>
    </>
  );
}
